version: '3'
services:

  chess-server:
    build:
      context: .
      dockerfile: ./Server/Dockerfile
    ports:
      - "5111:5000"

  computer-opponent:
    build:
      context: .
      dockerfile: ./Computer/Dockerfile
    ports:
      - "5112:5000"

  chess-engine:
    build:
      context: .
      dockerfile: ./Engine/Dockerfile
    ports:
      - "5114:5000"

  access:
    build:
      context: .
      dockerfile: ./Access/Dockerfile
    ports:
      - "5115:5000"

  accounts:
    build:
      context: .
      dockerfile: ./accounts/Dockerfile
    ports:
      - "5116:5000"

  game-master:
    build:
      context: .
      dockerfile: ./game-master/Dockerfile
    ports:
      - "5117:5000"

  shared-editor-db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5113:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db:/var/lib/mysql
# Names our volume
volumes:
  db: