CREATE DATABASE IF NOT EXISTS access;
GRANT ALL PRIVILEGES ON access.* TO 'root'@'%' WITH GRANT OPTION;
CREATE DATABASE IF NOT EXISTS accounts;
GRANT ALL PRIVILEGES ON accounts.* TO 'root'@'%' WITH GRANT OPTION;